nohup python3 -u ./memn2n/main.py \
    -root "./data/QA_bAbI_tasks/en-valid-10k/" \
    -task 1 \
    -bs 32 \
    -cuda \
    -emd 20 \
    -wstyle "rnnlike" \
    -encmth "pe" \
    -temporal \
    -thres 5 \
    -lr 0.01 \
    -stp 100 \
    -anl 0.5 \
    -save \
    -savebest \
    -svp "./saved_models/rnnlike/pe_te/taks1.model" > ./trainlog/rnnlike/pe_te/task1.log &
